name: gatsby-drupal-adventure
recipe: drupal9
config:
  webroot: ./web
services:
  appserver:
    build_as_root:
      - >
        apt-get update -y
        && apt-get upgrade -y
        && curl -fsSL https://deb.nodesource.com/setup_16.x | bash
        && apt install -y nodejs

    build:
      - >
        touch /var/www/.bashrc
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  elasticsearch:
      type: elasticsearch:7
tooling:
  blt:
    service: appserver
  npm:
    service: appserver
  npx:
    service: appserver